sudo: required
service:
 - docker
before_install:
  - docker build -t alagarsamy89/travis .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push alagarsamy89/travis:v2.0
notifications:
 email:
   recipients:
     - a.alagarsamy89@gmail.com
   on_success: always
   on_failure: always
